In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Model Evaluation and optimization

In the steps of machine learning you:
1. take data
2. build a model
3. evaluate a model
4. optimize it
5. rebuild if needed
Then lookst at new data and the prediction

### Accuracy

Usually the main goal is to make accurate predictions. One measure of performance on a model is how well tha t5model will perform on new data. 

#### Overfitting & model optimism

#### Cross-validation

holdout method because a random subset of the training data is held out from the training process. So you use a training subset to fit the model and only the testing subset to evaluate the accuracy of the model. 

Leave out 20 - 40$ of the data as the testing subset. 



In [2]:
#make up some data
features = rand(100,5)
target = rand(100) > 0.5

In [10]:
#holdout method
N = features.shape[0]
print(N)
N_train = int(floor(0.7 * N))
print(N_train)
#do this step if you want to randomize the index
idx = random.permutation(N)


100
70


In [13]:
#split to training/test
idx_train = idx[:N_train]
idx_test = idx[N_train:]

In [16]:
#split into subsets
features_train = features[idx_train,:]
target_train = target[idx_train]
features_test = features[idx_test,:]
target_test = target[idx_test]

#Then do rest of the machine learning stuff i.e.
#model = train(features_train, target_train)
#preds_test = predict(model, features_test)
#accuracy = evaluate_accuracy(preds_test, target_test)

#### k-fold cross-validation

just like holdout you have to split subsets of training data during the learning process. The difference is k-old begins by randomly splitting the data into k disjoint subsets, called folds. Typically (5, 10, 20)

The predictions are aggregated after all the cycles have been completed. 

In [17]:
#examle
N = features.shape[0]
K = 10 #number of folds you want

preds_kfold = np.empty(N)
folds = np.random.randint(0, K, size=N)

In [20]:
for idx in np.arange(K):
    #each fold break the data into training and testin gsubsets
    features_train = features[folds != idx, :]
    target_train = target[folds != idx]
    features_test = features[folds == idx, :]
    
    print(nonzero(folds == idx)[0])
    
    #build and predict
    #model = train(features_train, target_train)
    #preds_kfold[folds == idx] = predict(model, features_test)
#accuracy = evaluate_acc(preds_kfold, target)

[ 0 36 82 88 99]
[ 4 17 46 53 54 58 63 65 69 74]
[ 5  7 15 22 24 26 27 28 29 37 42 50 55 67 89]
[ 9 21 31 38 40 41 43 56 59 66 70 71 73 93 96]
[ 1 25 30 75 77 84 87 94]
[ 2 12 23 47 49 51 83 85 86 98]
[ 6 16 18 20 32 35 39 45 48 68 72 78 80 90]
[11 33 62 76 81 92 95 97]
[ 8 10 34 44 52 60 79 91]
[ 3 13 14 19 57 61 64]


#### Cross-validation

Gives you a way to estimate how accurately your ML models will predict when deployed in the wild. Things to look out for

1. CV methods assume that the training data forms a representative smaple from the population of interest. If you plan to deploy te modle to predict on new data, that data should be well represented by the training data. if not, the cross-validation error estimates may be overly optimistic for the error rates on future data. Solution: Ensure that any potential biases in the training data are addressed and minimized. 
2. Some datasets use features that are temporal-- for instance, using last month's revenue to forecast this month's revenue. If this is the case with your data, you must ensure that features that are available in the future can never be used to predict the past. Solution: you can structure your cross-validation holdout set or k-folds so that all the training set data is collected previous to the testing set. 
The larger the number of folds used in k-fold the better the error estimates will be, but the longer your program will take to run. Solution: use at least 10 folds (or more) when you can. For modles that train and predict quickly, you can use leave-one-out CV (k = number of data instances)
